version: '3'
services:
 web:
  container_name: vijaydev
  image: "vijay2181/productimage:01"  
  ports:
  - "8080:8080"
  volumes:
  - ./sanity:/var/log/vijay
  restart: always
  command: -Djboss.server.log.dir=/var/log/vijay
  depends_on:
    - redis
 redis:
  container_name: vijaydevdb
  image: "redis:alpine"
  ports:
  - "6379:6379"
